### ISSUE TITLE
Change font family to Open Sans

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast-mega-map#15]
Office name and subheaders: Open Sans Semibold 600

Address and other text: Open Sans Light 300

https://www.google.com/fonts/specimen/Open+Sans

**Comment by rhewitt22** [comment]
Is that what we're using on the main site?

Taking a look at the source files it looks like it's currently Source Sans

https://fonts.google.com/specimen/Source+Sans+Pro

If you want to use Open Sans can you add an issue to the Southeast repository, too?

**Comment by rhewitt22** [comment]
Closed via 9dd728134fe76662c47e97946ce34469d6c00d8f
