### ISSUE TITLE
Use metadata to pull office descriptions?

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast-mega-map#18]
"Right now we have a few w/narrative and activities (try Banks Lake in the search box) are we going to carry that through all of the offices?  Who is going to produce that?"

When a user clicks on a station, can you use the metadata from their webpage to pull in a description of that station?

**Comment by rhewitt22** [comment]
@jenmstrick That's possible, but pretty hacky.  I'd have to have the application download the entire office homepage just to pull out a few lines of text, which would be kinda slow and heavy on data usage.  Plus I've noticed that, for the most part, webpage meta descriptions are the same generic lines about being a conservation agency and the states we cover as a region.

**Comment by jenmstrick** [comment]
UGH. I had a feeling our metadata would be crappy.

If I produce this info, do you want me to put it directly into the code, or do it some other way?

**Comment by rhewitt22** [comment]
We might as well do this [as a spreadsheet](https://docs.google.com/a/doi.gov/spreadsheets/d/18UuXOHGimtACuPqSatHVsiG7IjOxodxr2KDjkQSdPZw/edit?usp=sharing) so it's easy to maintain, and we know where to find it.  Doing all of this in the code would be a nightmare.

The good news is we're creating _**real**_ meta descriptions for all of the new pages we've been creating so we won't repeat the same mistake twice.

**Comment by rhewitt22** [comment]
Closing due to fact we can't responsibly use meta tag from pages to fill out this data.
